# Generated by Django 4.2 on 2025-05-05 11:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipient', '0001_initial'),
        ('cities', '0001_initial'),
        ('clients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('client_invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Invoice Number')),
                ('notes_customer', models.TextField(blank=True, null=True, verbose_name='ملاحظات العميل')),
                ('notes_recipient', models.TextField(blank=True, null=True, verbose_name='ملاحظات المستلم')),
                ('fare', models.IntegerField(verbose_name='Fare')),
                ('premium', models.IntegerField(blank=True, null=True, verbose_name='Premium')),
                ('fare_return', models.IntegerField(blank=True, null=True, verbose_name='Return')),
                ('days_stayed', models.IntegerField(blank=True, null=True, verbose_name='Days Stayed')),
                ('stay_cost', models.IntegerField(blank=True, null=True, verbose_name='Stay Cost')),
                ('deducted', models.IntegerField(blank=True, null=True, verbose_name='Deducted')),
                ('loading_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ التحميل')),
                ('days_to_arrive', models.IntegerField(blank=True, default=3, null=True, verbose_name='عدد الأيام  الوصول')),
                ('expected_arrival_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الوصول المتوقع')),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الوصول الفعلي')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='وزن الشحنة (طن)')),
                ('contents', models.TextField(blank=True, null=True, verbose_name='محتويات الشحنة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ الانشاء')),
                ('loading_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التحميل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_customer', to='clients.client')),
                ('client_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_company', to='clients.branch')),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_shipments', to='cities.city', verbose_name='مدينة الوجهة')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_driver', to='drivers.driver')),
                ('origin_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_shipments', to='cities.city', verbose_name='مدينة التحميل')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_recipient', to='recipient.recipient')),
            ],
            options={
                'verbose_name': 'الشحنه',
                'verbose_name_plural': 'الشحنات',
            },
        ),
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, verbose_name='الحالة')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'حالة الشحنة',
                'verbose_name_plural': 'حالات الشحنات',
            },
        ),
        migrations.CreateModel(
            name='ShipmentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='shipments.shipment')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.shipmentstatus')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تاريخ الشحنه',
                'verbose_name_plural': 'تواريخ الشحنات',
            },
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.shipmentstatus', verbose_name='الحالة'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
