# Generated by Django 5.1.4 on 2025-02-07 06:54

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_alter_branch_city'),
        ('drivers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ShipmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_en', models.CharField(max_length=50, verbose_name='الحالة')),
                ('name_ar', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True)),
                ('fare', models.IntegerField(verbose_name='Fare')),
                ('premium', models.IntegerField(blank=True, null=True, verbose_name='Premium')),
                ('fare_return', models.IntegerField(blank=True, null=True, verbose_name='Return')),
                ('code', models.ImageField(blank=True, null=True, upload_to='code')),
                ('days_stayed', models.IntegerField(blank=True, null=True, verbose_name='Days Stayed')),
                ('stay_cost', models.IntegerField(blank=True, null=True, verbose_name='Stay Cost')),
                ('deducted', models.IntegerField(blank=True, null=True, verbose_name='Deducted')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created At')),
                ('expected_arrival_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Expected Arrival Date')),
                ('actual_delivery_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Actual Delivery Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('customer_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_company', to='clients.branch')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_driver', to='drivers.driver')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_user', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipments.shipmentstatus', verbose_name='الحالة')),
            ],
            options={
                'verbose_name': 'Shipment',
                'verbose_name_plural': 'Shipments',
            },
        ),
    ]
