# Generated by Django 5.1.4 on 2025-02-09 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0002_alter_recipient_address_alter_recipient_email_and_more'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'verbose_name': 'الشحنه', 'verbose_name_plural': 'الشحنات'},
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_recipient', to='recipient.recipient'),
        ),
    ]
