# Generated by Django 5.1.6 on 2025-05-22 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='recipient',
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient',
            field=models.ManyToManyField(blank=True, related_name='shipments_recipient', to='recipient.recipient'),
        ),
    ]
