<<<<<<< HEAD
# Generated by Django 5.1.6 on 2025-06-14 17:53
=======
# Generated by Django 5.1.6 on 2025-06-14 17:48
>>>>>>> d34e6f451a9a4b4750aad6f886d1e67278ea8857

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='truck_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_truck_type', to='drivers.trucktype'),
        ),
    ]
