# Generated by Django 5.1.6 on 2025-06-19 23:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_shipment_truck_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipmenthistory',
            name='action',
            field=models.CharField(default='PUT', max_length=10),
        ),
        migrations.AddField(
            model_name='shipmenthistory',
            name='new_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='new_histories', to='shipments.shipmentstatus'),
        ),
        migrations.AlterField(
            model_name='shipmenthistory',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_histories', to='shipments.shipmentstatus'),
        ),
    ]
