# Generated by Django 5.1.4 on 2025-02-09 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_alter_shipment_options_shipment_recipient'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='days_to_arrive',
            field=models.IntegerField(blank=True, default=3, null=True, verbose_name='Days to Arrive'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Actual Delivery Date'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='expected_arrival_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Expected Arrival Date'),
        ),
    ]
