# Generated by Django 5.1.6 on 2025-05-25 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
        ('shipments', '0002_remove_shipment_recipient_shipment_recipient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='recipient',
        ),
        migrations.AddField(
            model_name='shipment',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_recipient', to='recipient.recipient'),
        ),
    ]
