# Generated by Django 5.1.4 on 2025-02-09 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipment_days_to_arrive_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipmentstatus',
            options={'verbose_name': 'حالة الشحنة', 'verbose_name_plural': 'حالات الشحنات'},
        ),
        migrations.AddField(
            model_name='shipment',
            name='customer_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Invoice Number'),
        ),
    ]
