# Generated by Django 5.1.6 on 2025-06-19 23:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_shipmenthistory_action_shipmenthistory_new_status_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipmenthistory',
            old_name='status',
            new_name='old_status',
        ),
    ]
