# Generated by Django 4.2 on 2025-03-09 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_options'),
        ('shipments', '0004_alter_shipmentstatus_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='destination_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_shipments', to='cities.city', verbose_name='مدينة الوجهة'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_shipments', to='cities.city', verbose_name='مدينة التحميل'),
        ),
    ]
