# Generated by Django 5.1.6 on 2025-06-27 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_rename_status_shipmenthistory_old_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='driver_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم هاتف السائق'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vehicle_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم المركبة'),
        ),
    ]
