# Generated by Django 4.2 on 2025-03-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_destination_city_shipment_origin_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentstatus',
            name='name_ar',
            field=models.CharField(max_length=50, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='shipmentstatus',
            name='name_en',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
    ]
