# Generated by Django 5.1.6 on 2025-04-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_destination_city_shipment_origin_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
