# Generated by Django 5.1.6 on 2025-07-19 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0001_initial'),
        ('shipments', '0005_shipment_driver_phone_number_shipment_vehicle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='recipient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_recipient', to='recipient.recipient'),
        ),
    ]
