# Generated by Django 4.2 on 2025-03-20 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_alter_shipmentstatus_name_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipmentstatus',
            name='name_ar',
            field=models.CharField(max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='shipmentstatus',
            name='name_en',
            field=models.CharField(max_length=50, verbose_name='الحالة'),
        ),
    ]
