# Generated by Django 4.2 on 2025-04-17 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_shipmenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='contents',
            field=models.TextField(blank=True, null=True, verbose_name='محتويات الشحنة'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن الشحنة (كجم)'),
        ),
    ]
