# Generated by Django 4.2 on 2025-04-07 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_shipment_updated_at'),
        ('shipments', '0008_alter_shipmentstatus_name_ar_and_more'),
    ]

    operations = [
    ]
