# Generated by Django 5.1.6 on 2025-04-20 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_remove_shipment_code_shipment_loading_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن الشحنة (طن)'),
        ),
    ]
