# Generated by Django 4.2 on 2025-04-12 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_shipmenthistory'),
        ('shipments', '0009_merge_20250407_2042'),
    ]

    operations = [
    ]
