# Generated by Django 4.2 on 2025-04-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0007_client_second_phone_number'),
        ('shipments', '0010_alter_shipment_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='customer_branch',
            new_name='client_branch',
        ),
        migrations.AddField(
            model_name='shipment',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipments_customer', to='clients.client'),
        ),
    ]
