# Generated by Django 4.2 on 2025-04-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0008_shipment_contents_shipment_weight'),
        ('shipments', '0010_merge_0007_shipmenthistory_0009_merge_20250407_2042'),
    ]

    operations = [
    ]
