# Generated by Django 4.2 on 2025-04-18 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0009_remove_shipment_code_shipment_loading_date_and_more'),
        ('shipments', '0011_merge_20250417_1836'),
    ]

    operations = [
    ]
