# Generated by Django 4.2 on 2025-04-26 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0011_rename_customer_branch_shipment_client_branch_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='customer_invoice_number',
            new_name='client_invoice_number',
        ),
    ]
