# Generated by Django 4.2 on 2025-04-26 10:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_rename_customer_invoice_number_shipment_client_invoice_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='loading_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاريخ التحميل'),
        ),
    ]
