# Generated by Django 4.2 on 2025-04-18 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0012_merge_20250418_0523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='وزن الشحنة (طن)'),
        ),
    ]
