# Generated by Django 4.2 on 2025-04-20 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0010_alter_shipment_weight'),
        ('shipments', '0013_alter_shipment_weight'),
    ]

    operations = [
    ]
