# Generated by Django 4.2 on 2025-04-26 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0013_shipment_loading_at'),
        ('shipments', '0014_merge_20250420_1907'),
    ]

    operations = [
    ]
