# Generated by Django 5.1.4 on 2025-02-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم السائق')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('nationality', models.CharField(max_length=100, verbose_name='الجنسية')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('ur', 'Urdu')], default='en', max_length=20, verbose_name='اللغة')),
                ('identity_number', models.CharField(max_length=20, verbose_name='رقم الهوية')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='رقم المركبة')),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=10, verbose_name='حالة السائق')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقين',
            },
        ),
    ]
