# Generated by Django 5.1.6 on 2025-05-17 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=100, verbose_name='نوع الشاحنة')),
                ('name_en', models.CharField(max_length=100, verbose_name='Truck_Type')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'نوع الشاحنة',
                'verbose_name_plural': 'أنواع الشاحنات',
            },
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم السائق')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('nationality', models.CharField(max_length=100, verbose_name='الجنسية')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('ur', 'Urdu')], default='en', max_length=20, verbose_name='اللغة')),
                ('identity_number', models.CharField(max_length=20, verbose_name='رقم الهوية')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='رقم المركبة')),
                ('status', models.CharField(choices=[('available', 'Available'), ('busy', 'Busy'), ('offline', 'Offline')], default='available', max_length=10, verbose_name='حالة السائق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('truck_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.trucktype', verbose_name='نوع الشاحنة')),
            ],
            options={
                'verbose_name': 'سائق',
                'verbose_name_plural': 'السائقين',
            },
        ),
    ]
