# Generated by Django 5.1.6 on 2025-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('offline', 'Offline')], default='available', max_length=10, verbose_name='حالة السائق'),
        ),
    ]
