# Generated by Django 4.2 on 2025-04-17 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0003_driver_created_at_driver_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TruckType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نوع الشاحنة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='الوصف')),
            ],
            options={
                'verbose_name': 'نوع الشاحنة',
                'verbose_name_plural': 'أنواع الشاحنات',
            },
        ),
        migrations.AddField(
            model_name='driver',
            name='truck_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='drivers.trucktype', verbose_name='نوع الشاحنة'),
        ),
    ]
