# Generated by Django 4.2 on 2025-04-26 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0005_driver_is_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trucktype',
            old_name='name',
            new_name='name_ar',
        ),
        migrations.AddField(
            model_name='trucktype',
            name='name_en',
            field=models.CharField(default=1, max_length=100, verbose_name='Truck_Type'),
            preserve_default=False,
        ),
    ]
