# Generated by Django 5.1.6 on 2025-05-05 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم العميل')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='العنوان')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('second_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف الثاني')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='البريد الإلكتروني')),
                ('Commercial_registration_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري')),
                ('dicription', models.TextField(blank=True, null=True, verbose_name='وصف')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
            },
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم الفرع')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
                ('name_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم العنوان')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف')),
                ('second_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف الثاني')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='cities.city', verbose_name='المدينة')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='clients.client', verbose_name='العميل')),
            ],
            options={
                'verbose_name': 'فرع',
                'verbose_name_plural': 'الفروع',
            },
        ),
    ]
