# Generated by Django 5.1.4 on 2025-02-07 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='country',
        ),
    ]
