# Generated by Django 5.1.4 on 2025-02-07 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('clients', '0002_remove_branch_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to='cities.city', verbose_name='المدينة'),
        ),
    ]
