# Generated by Django 5.1.6 on 2025-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_alter_branch_address_alter_branch_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='name_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم العنوان'),
        ),
        migrations.AddField(
            model_name='client',
            name='dicription',
            field=models.TextField(blank=True, null=True, verbose_name='وصف'),
        ),
    ]
