# Generated by Django 5.1.6 on 2025-04-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_branch_name_address_client_dicription'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف الثاني'),
        ),
        migrations.AddField(
            model_name='client',
            name='Commercial_registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم السجل التجاري'),
        ),
    ]
