# Generated by Django 5.1.6 on 2025-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_branch_second_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف الثاني'),
        ),
    ]
