# Generated by Django 4.2 on 2025-03-09 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'صفجة المستخدم', 'verbose_name_plural': 'صفحات المستخدمين'},
        ),
    ]
