# Generated by Django 5.1.6 on 2025-05-08 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('profile_company', '0004_companybranch_branch_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='company_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_company_branch', to='profile_company.companybranch'),
        ),
    ]
