# Generated by Django 4.2 on 2025-05-05 12:08

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_customuser_company_branch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='company_branch',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company_branch',
            field=models.ForeignKey(
                'profile_company.CompanyBranch',
                related_name='user_company_branch',
                on_delete=models.SET_NULL,
                blank=True,
                null=True,
                verbose_name='Company Branch'
            ),
        ),
    ]
