# Generated by Django 5.1.6 on 2025-05-08 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_customuser_company_branch'),
    ]

    operations = [
    ]
