# Generated by Django 4.2 on 2025-05-05 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_company', '0002_companybranch_branch_manager'),
        ('accounts', '0003_remove_company_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_company_branch', to='profile_company.companybranch'),
        ),
    ]
