# Generated by Django 5.1.6 on 2025-06-27 19:59
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        ('clients', '0001_initial'),
        ('drivers', '0001_initial'),
        ('profile_company', '0001_initial'),
        ('recipient', '0001_initial'),
        ('shipments', '0004_rename_status_shipmenthistory_old_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التتبع')),
                ('client_invoice_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Invoice Number')),
                ('actual_delivery_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الوصول الفعلي')),
                ('fare', models.IntegerField(blank=True, null=True, verbose_name='Fare')),
                ('premium', models.IntegerField(blank=True, null=True, verbose_name='Premium')),
                ('fare_return', models.IntegerField(blank=True, null=True, verbose_name='Return')),
                ('days_stayed', models.IntegerField(blank=True, null=True, verbose_name='Days Stayed')),
                ('stay_cost', models.IntegerField(blank=True, null=True, verbose_name='Stay Cost')),
                ('deducted', models.IntegerField(blank=True, null=True, verbose_name='Deducted')),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافقة')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='معتمد السند')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_client', to='clients.client')),
                ('client_branch', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_client_branch', to='clients.branch')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='منشئ السند')),
                ('destination_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_payment_vouchers', to='cities.city', verbose_name='مدينة الوجهة')),
                ('driver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_driver', to='drivers.driver', verbose_name='السائق')),
                ('issuing_branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_payment_vouchers', to='profile_company.companybranch', verbose_name='فرع الإصدار')),
                ('origin_city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_payment_vouchers', to='cities.city', verbose_name='مدينة التحميل')),
                ('receiver_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payment_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='مستلم المبلغ')),
                ('recipient', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_recipient', to='recipient.recipient')),
                ('shipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_voucher', to='shipments.shipment', verbose_name='الشحنة المرتبطة')),
            ],
            options={
                'verbose_name': 'سند صرف',
                'verbose_name_plural': 'سندات الصرف',
            },
        ),
    ]
