# Generated by Django 5.1.6 on 2025-06-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_vouchers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='days_stayed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Days Stayed'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='deducted',
            field=models.IntegerField(blank=True, null=True, verbose_name='Deducted'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='fare',
            field=models.IntegerField(default=100, verbose_name='Fare'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='fare_return',
            field=models.IntegerField(blank=True, null=True, verbose_name='Return'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='premium',
            field=models.IntegerField(blank=True, null=True, verbose_name='Premium'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='stay_cost',
            field=models.IntegerField(blank=True, null=True, verbose_name='Stay Cost'),
        ),
    ]
