# Generated by Django 5.1.6 on 2025-07-05 20:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_vouchers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='is_approved',
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='مستلم المبلغ'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='rejection_reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='سبب الرفض'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_payment_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='مراجع السند'),
        ),
    ]
