# Generated by Django 5.1.6 on 2025-07-05 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_vouchers', '0002_remove_paymentvoucher_is_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentvoucher',
            name='approved_by',
        ),
    ]
