# Generated by Django 5.1.6 on 2025-06-20 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_vouchers', '0002_paymentvoucher_days_stayed_paymentvoucher_deducted_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='fare',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fare'),
        ),
    ]
