# Generated by Django 5.1.6 on 2025-06-20 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_vouchers', '0003_alter_paymentvoucher_fare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentvoucher',
            old_name='creator',
            new_name='created_by',
        ),
    ]
