# Generated by Django 5.1.6 on 2025-07-05 21:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_vouchers', '0003_remove_paymentvoucher_approved_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='حالة السند'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='receiver_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payment_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='المستلم'),
        ),
    ]
