# Generated by Django 5.1.6 on 2025-07-12 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('payment_vouchers', '0004_alter_paymentvoucher_approval_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentvoucher',
            name='receiver_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payment_vouchers', to='drivers.driver', verbose_name='المستلم'),
        ),
    ]
