# Generated by Django 5.1.6 on 2025-06-22 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
        ('clients', '0001_initial'),
        ('payment_vouchers', '0004_rename_creator_paymentvoucher_created_by'),
        ('recipient', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='actual_delivery_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الوصول الفعلي'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_client', to='clients.client'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='client_branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_client_branch', to='clients.branch'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='client_invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Customer Invoice Number'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='destination_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_payment_vouchers', to='cities.city', verbose_name='مدينة الوجهة'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='موافقة'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='origin_city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_payment_vouchers', to='cities.city', verbose_name='مدينة التحميل'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_recipient', to='recipient.recipient'),
        ),
    ]
