# Generated by Django 5.1.6 on 2025-06-22 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_vouchers', '0005_paymentvoucher_actual_delivery_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_payment_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='معتمد السند'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='receiver_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payment_vouchers', to=settings.AUTH_USER_MODEL, verbose_name='مستلم المبلغ'),
        ),
    ]
