# Generated by Django 5.1.6 on 2025-07-12 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_vouchers', '0005_alter_paymentvoucher_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='receiver_identity',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم الهوية'),
        ),
        migrations.AddField(
            model_name='paymentvoucher',
            name='receiver_phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم المستلم'),
        ),
    ]
