# Generated by Django 5.1.6 on 2025-06-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_vouchers', '0006_paymentvoucher_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='رقم الشحنة'),
        ),
    ]
