# Generated by Django 5.1.6 on 2025-06-25 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0001_initial'),
        ('payment_vouchers', '0006_paymentvoucher_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='driver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_vouchers_driver', to='drivers.driver', verbose_name='السائق'),
        ),
    ]
