# Generated by Django 5.1.6 on 2025-06-25 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_vouchers', '0007_paymentvoucher_driver'),
        ('shipments', '0004_rename_status_shipmenthistory_old_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم التتبع'),
        ),
        migrations.AlterField(
            model_name='paymentvoucher',
            name='shipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_voucher', to='shipments.shipment', verbose_name='الشحنة المرتبطة'),
        ),
    ]
