# Generated by Django 5.1.6 on 2025-06-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_vouchers', '0008_paymentvoucher_tracking_number_and_more'),
        ('profile_company', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentvoucher',
            name='issuing_branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_payment_vouchers', to='profile_company.companybranch', verbose_name='فرع الإصدار'),
        ),
    ]
