# Generated by Django 5.1.4 on 2025-02-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ar_city', models.CharField(max_length=255, unique=True, verbose_name='المدينة')),
                ('en_city', models.CharField(max_length=255, unique=True, verbose_name='City')),
            ],
        ),
    ]
