# Generated by Django 5.1.4 on 2025-02-09 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'المدن', 'verbose_name_plural': 'المدن'},
        ),
    ]
