# Generated by Django 4.2 on 2025-05-05 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشركة')),
                ('company_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='company_logos/')),
                ('company_description_ar', models.TextField(blank=True, null=True, verbose_name='وصف الشركة')),
                ('company_description_en', models.TextField(blank=True, null=True, verbose_name='Company Description')),
                ('main_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الأساسي')),
                ('secondary_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الفرعي')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني')),
                ('website', models.URLField(blank=True, null=True, verbose_name='الموقع الالكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city')),
            ],
            options={
                'verbose_name': ' ملف شركة ',
                'verbose_name_plural': 'بيانات الشركة',
            },
        ),
        migrations.CreateModel(
            name='CompanyBranch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الفرع')),
                ('branch_name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch Name')),
                ('main_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الأساسي')),
                ('secondary_phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الفرعي')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='profile_company.companyprofile')),
            ],
            options={
                'verbose_name': ' الفرع',
                'verbose_name_plural': ' الفروع ',
            },
        ),
    ]
