# Generated by Django 4.2 on 2025-05-05 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_company', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='main_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الأساسي'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الفرعي'),
        ),
    ]
