# Generated by Django 5.1.6 on 2025-05-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_company', '0002_remove_companyprofile_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companybranch',
            options={'verbose_name': ' الفرع', 'verbose_name_plural': ' الفروع '},
        ),
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': ' ملف شركة ', 'verbose_name_plural': ' ملفات الشركات'},
        ),
        migrations.RemoveField(
            model_name='companybranch',
            name='branch_name',
        ),
        migrations.RemoveField(
            model_name='companybranch',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_description',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='companybranch',
            name='branch_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الفرع'),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='branch_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Branch Name'),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='main_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الأساسي'),
        ),
        migrations.AddField(
            model_name='companybranch',
            name='secondary_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='الرقم الفرعي'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='وصف الشركة'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Company Description'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='اسم الشركة'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='company_name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الالكتروني'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='الموقع الالكتروني'),
        ),
        migrations.DeleteModel(
            name='UserPermission',
        ),
    ]
