# Generated by Django 5.1.6 on 2025-05-08 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_company', '0002_companybranch_branch_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companybranch',
            name='branch_manager',
        ),
    ]
