# Generated by Django 5.1.6 on 2025-05-05 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_city_options'),
        ('profile_company', '0003_alter_companybranch_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyprofile',
            options={'verbose_name': ' ملف شركة ', 'verbose_name_plural': 'بيانات الشركة'},
        ),
        migrations.AlterField(
            model_name='companybranch',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.city'),
        ),
    ]
