# Generated by Django 5.1.4 on 2025-02-07 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='اسم المستلم')),
                ('phone_number', models.CharField(max_length=20, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('address', models.TextField(blank=True, null=True, verbose_name='العنوان')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='cities.city', verbose_name='المدينة')),
            ],
            options={
                'verbose_name': 'مستلم',
                'verbose_name_plural': 'المستلمين',
            },
        ),
    ]
