# Generated by Django 5.1.6 on 2025-04-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipient', '0002_alter_recipient_address_alter_recipient_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='second_phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='رقم الهاتف الثاني'),
        ),
    ]
